### ISSUE TITLE
k8s backendでコンテナのStatusがRestartingにならない

### ISSUE THREAD

**Issue by motoki317** [traPtitech/NeoShowcase#725]
再起動を繰り返していても(backoff restartingでも)、ずっとStartingになっている

**Comment by motoki317** [comment]
memo
こんな感じになる
```
  containerStatuses:
    - name: app
      state:
        waiting:
          reason: CrashLoopBackOff
          message: >-
            back-off 5m0s restarting failed container=app
            pod=nsapp-fa868e46640f566de09528-0_ns-apps(927c8906-679e-4ccb-9e2d-e219eada6de0)
      lastState:
        terminated:
          exitCode: 1
          reason: Error
          startedAt: '2023-09-24T11:55:44Z'
          finishedAt: '2023-09-24T11:55:46Z'
          containerID: >-
            containerd://d9aa34b012e737d7fcb4964e1c556c9c2c6284a37bf05a5a89a09bddb8efe04c
      ready: false
      restartCount: 617
      image: >-
        registry.ns.trap.jp/ns-apps/fa868e46640f566de09528:e609eddd3a8ec4c6332294
      imageID: >-
        registry.ns.trap.jp/ns-apps/fa868e46640f566de09528@sha256:bee13877536cb7d15643dae6a8fd71160961b9f23ab2601fbf4ee6e44eff7d4b
      containerID: >-
        containerd://d9aa34b012e737d7fcb4964e1c556c9c2c6284a37bf05a5a89a09bddb8efe04c
      started: false
```
